### PR TITLE
Add vision, mission and community value statements

### LINKED ISSUE #7: add vision and community mission statements

### PR DESCRIPTION
**Pull request by ivotron**
Adding a first version of vision, mission and community value statements. For the community value ones, I am following Jono Bacon's recommendation of keeping short (3-4 max.), and these essential need to answer concisely the question of "what's in it for me?" (where "me" is a potential member of our community).

fixes #7

### CODE REVIEW

**Comment by ivotron** [comment]
If you have time, can you please take a look and express any comments/questions you may have? It'd be greatly appreciated!! 🙏 

@wtraylor, @JayjeetAtGithub, @FernandaDguez, @Jswig , @nicolecastillo, @edeediong, @carlosmalt, @UjjwalAyyangar, @ankan17, @eltrufas, @Franko1307, @luizirber, @michaelsevilla, @qwofford, @arshul, @felix11h

**Comment by ivotron** [comment]
the preview for this PR is available here: https://deploy-preview-10--getpopper.netlify.app/community/

**Comment by edeediong** [comment]
Hi Ivo! I'm not exactly a great UI person but I think the texts from Vision, Mission and Community Values should align... Like the very first line. I do like the concept behind the listing in Community Values though. 

I'll ask a UI Designer friend of mine to take a look.

**Comment by ivotron** [comment]
thanks @edeediong! Sorry for the confusion, I meant to say that I was seeking feedback on the content of the statements, although feedback on the UI is more than welcome as well!

**Comment by carlosmalt** [comment]
> Vision: Tear down technical barriers to enable everyone to collaborate in software projects.

Vision is a future state: e.g. "Nobody gets burned by hours of frustrating trial and error when learning how to contribute to a software project."

> Mission: Create and maintain a suite of container-native tools to minimize technical friction in software projects.

Create and maintain tools that allow everyone to touch hot-off-the-griddle software without getting burned.

> Community Values:
>     1. Meet other people interested in issues relevant to the container-native paradigm practice.
>     2. Acquire knowledge that is otherwise difficult to attain elsewhere.
>     3. Minimize waste, both in terms of time and resources. 

Looks good!

**Comment by arshul** [comment]
Hey @ivotron, I also would like to suggest some UI enhancements, I think the Headings should have some contrast from the details also center-aligned is not very readable.
The points can be made in bullets instead of numbers in the community values section

Before
Screenshot from 2020-11-10 13-15-21

After
Screenshot from 2020-11-10 13-08-06

**Comment by michaelsevilla** [comment]
I agree with @carlosmalt 's comments:
- 👍  for the theme of tying the mission and vision with a cute metaphor; we should keep that! I see lots of "Uber for x" or "Airbnb for y" so this follows those themes.
- I'm hesitating with whether "burned" is the right word... (1) the metaphor feels like a stretch (I had to think about it for a little bit) and we really want to emphasize that we "waste" time, $, and effort not that we got burned by investing time, $, and effort, and (2) it might be better to spin it as a positive rather than negative (fear shouldn't be a motivating factor for picking up a piece of software), focusing on the zero-to-hero aspect of the project. I need to think on it more...

I think the community statements are good in content but could be tightened up and aimed at passionate people:
1. ~Meet other~ **Engage** ~people interested in issues relevant to the container-native~ **with other container-enthusiasts over the most useful** paradigm practices. You could even go really strong here with:
    > Engage with other container-enthusiasts to showcase the power of paradigm practices.
2. ~Acquire knowledge~ **Grow with a community** ~on  that is otherwise difficult to attain elsewhere~ **hell-bent on attaining cutting-edge, yet use-case appropriate, knowledge**.
3. This is good.

Ugh this is harder than it looks. Sorry for the rambling thoughts.

**Comment by ivotron** [comment]
thanks everybody for your feedback! 🙏 

I made changes based on it. The main thing I'd like to emphasize (in mission and value) is the focus on the container-native paradigm since that's the main technical foundation for the tools and practices. I'll go ahead and merge but please feel free to open an issue if you think there's something that should be changed.

**Pull request merged**
